# Generated by Django 5.2.9 on 2025-12-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_product_category_remove_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('shirts', 'Shirts'), ('tshirts', 'T-Shirts'), ('jeans', 'Jeans'), ('ethnic', 'Ethnic Wear'), ('kurtis', 'Kurtis'), ('dresses', 'Dresses'), ('tops', 'Tops')], default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('unisex', 'Unisex')], max_length=10),
        ),
    ]
