# Generated by Django 5.2.9 on 2025-12-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_category_alter_product_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
