# Generated by Django 5.2.9 on 2025-12-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sku',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sku',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
