# Generated by Django 5.2.9 on 2025-12-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_sku_color_alter_sku_price_alter_sku_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='sku_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
