# Generated by Django 5.2.9 on 2025-12-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_sku_sku_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='sku_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
