# Generated by Django 5.2.9 on 2025-12-30 11:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
