# Generated by Django 5.2.9 on 2025-12-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_sku_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sku',
            name='price',
        ),
        migrations.AddField(
            model_name='sku',
            name='mrp',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sku',
            name='selling_price',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
