# Generated by Django 5.2.9 on 2026-03-01 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_order_city_order_pincode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
