# Generated by Django 5.2.9 on 2026-03-01 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
