# Generated by Django 5.2.9 on 2026-03-01 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_remove_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Order Item', 'verbose_name_plural': 'Order Items'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='sku',
            options={'ordering': ['product', 'size'], 'verbose_name': 'SKU'},
        ),
        migrations.AlterModelOptions(
            name='stocknotification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Stock Notification'},
        ),
    ]
