# Generated by Django 5.2.9 on 2026-03-04 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_order_delivery_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_charge',
        ),
    ]
