# Generated by Django 5.2.9 on 2026-03-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_customer_remove_address_user_remove_order_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_enabled', models.BooleanField(default=True, help_text='Uncheck to disable COD and force all customers to pay online.', verbose_name='Cash on Delivery enabled')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
