# Generated by Django 5.2.9 on 2026-03-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_site_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='store_address',
            field=models.TextField(blank=True, default='', help_text='Full return/pickup address printed on shipping labels.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='store_name',
            field=models.CharField(default='Zivo Fashion Store', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='store_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
