# Generated by Django 5.2.9 on 2026-03-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_sitesettings_store_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('shirts', 'Shirts'), ('tshirts', 'T-Shirts'), ('jeans', 'Jeans'), ('ethnic', 'Ethnic Wear'), ('kurtis', 'Kurtis'), ('dresses', 'Dresses'), ('tops', 'Tops')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('unisex', 'Unisex')], db_index=True, max_length=10),
        ),
    ]
