# Generated by Django 5.2.9 on 2026-03-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_coupon_order_discount_amount_order_coupon_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='show_in_banner',
            field=models.BooleanField(default=False, help_text='Show this coupon in the site-wide announcement banner'),
        ),
    ]
