# Generated by Django 5.2.9 on 2026-03-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_add_coupon_show_in_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmation_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
