# Generated by Django 5.2.9 on 2026-03-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_category_model_and_product_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='delivery_charge',
            field=models.PositiveIntegerField(default=59, help_text='Flat delivery fee charged when order is below the free-delivery threshold.', verbose_name='Delivery charge (₹)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='free_delivery_min_order',
            field=models.PositiveIntegerField(default=799, help_text='Orders at or above this amount get free delivery.', verbose_name='Free delivery above (₹)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='gender',
            field=models.CharField(blank=True, choices=[('men', 'Men'), ('women', 'Women'), ('unisex', 'Unisex')], default='', help_text='Which nav dropdown this appears under. Leave blank to hide from nav.', max_length=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Lower number appears first in nav'),
        ),
    ]
