# Generated by Django 5.2.9 on 2026-03-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_sitesettings_delivery_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='offer_discount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('offer_type', models.CharField(choices=[('PERCENTAGE', 'Percentage Discount — X% off matching items'), ('BOGO', 'Buy 1 Get 1 Free — cheapest matching item is free'), ('BUY_X_GET_Y', 'Buy X Get Y — buy X, get Y items at a discount'), ('MIN_QTY', 'Minimum Quantity — buy min qty, get X% off')], max_length=20)),
                ('description', models.CharField(blank=True, help_text='Short label shown to the customer on cart and checkout pages. Leave blank to use the offer name.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('discount_percent', models.PositiveIntegerField(default=0, help_text='Discount % (1–100). Used for Percentage and Min Quantity offer types.')),
                ('buy_quantity', models.PositiveIntegerField(default=1, help_text='Number of items the customer must buy. (BUY X GET Y only)')),
                ('get_quantity', models.PositiveIntegerField(default=1, help_text='Number of items the customer gets at a discount. (BUY X GET Y only)')),
                ('get_discount_percent', models.PositiveIntegerField(default=100, help_text="Discount % on the 'get' items — 100 means completely free. (BUY X GET Y only)")),
                ('min_quantity', models.PositiveIntegerField(default=2, help_text='Minimum number of matching items needed to trigger the discount. (Min Quantity only)')),
                ('applicable_categories', models.ManyToManyField(blank=True, help_text='Restrict this offer to specific categories. Leave empty to apply to all.', related_name='offers', to='store.category', verbose_name='Applicable Categories')),
                ('applicable_products', models.ManyToManyField(blank=True, help_text='Restrict this offer to specific products. Leave empty to apply to all.', related_name='offers', to='store.product', verbose_name='Applicable Products')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
                'ordering': ['name'],
            },
        ),
    ]
