# Generated by Django 5.2.9 on 2026-03-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_product_is_trending'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Shown on the home page category tiles', null=True, upload_to='categories/'),
        ),
    ]
