# Generated by Django 5.2.9 on 2026-03-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Shown on the home page category tiles', max_length=255, null=True, upload_to='categories/'),
        ),
    ]
