# Generated by Django 5.2.9 on 2026-03-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_newsletter_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscriber',
            name='token',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
