# Generated by Django 5.2.9 on 2026-03-19 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_populate_newsletter_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='return_window_days',
            field=models.PositiveIntegerField(default=7, help_text='Number of days after delivery within which customers can request a return.', verbose_name='Return window (days)'),
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('SIZE_ISSUE', "Size issue / doesn't fit"), ('QUALITY_ISSUE', 'Quality not as expected'), ('WRONG_ITEM', 'Wrong item delivered'), ('DAMAGED', 'Item arrived damaged'), ('OTHER', 'Other')], max_length=20)),
                ('reason_detail', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REFUND_PROCESSED', 'Refund Processed')], default='REQUESTED', max_length=20)),
                ('admin_notes', models.TextField(blank=True, default='', help_text='Internal notes (not shown to customer).')),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('razorpay_refund_id', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_request', to='store.order')),
            ],
            options={
                'verbose_name': 'Return Request',
                'verbose_name_plural': 'Return Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_items', to='store.orderitem')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_items', to='store.returnrequest')),
            ],
            options={
                'verbose_name': 'Return Item',
                'verbose_name_plural': 'Return Items',
            },
        ),
    ]
