# Generated by Django 5.2.9 on 2026-03-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_sitesettings_return_window_days_returnrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='unboxing_video',
            field=models.FileField(blank=True, help_text='Unboxing video uploaded by customer as proof.', null=True, upload_to='return_videos/'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='reason',
            field=models.CharField(choices=[('WRONG_ITEM', 'Wrong item delivered'), ('DAMAGED', 'Item arrived damaged')], max_length=20),
        ),
    ]
