# Generated by Django 5.2.9 on 2026-03-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_returnrequest_unboxing_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnrequest',
            name='unboxing_video',
            field=models.URLField(blank=True, default='', help_text='Cloudinary URL of the unboxing video uploaded by customer.', max_length=500),
        ),
    ]
