# Generated by Django 5.2.9 on 2026-03-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_alter_returnrequest_unboxing_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='bank_account_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='bank_account_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='bank_ifsc',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='refund_via',
            field=models.CharField(blank=True, choices=[('UPI', 'UPI'), ('BANK', 'Bank Transfer')], default='', help_text='Preferred refund method for COD orders.', max_length=10),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='upi_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
