# Generated by Django 5.2.9 on 2026-03-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0050_productimage_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='care',
            field=models.CharField(blank=True, default='', help_text='e.g. "Machine wash cold, do not tumble dry"', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Shown on the product page. Supports basic HTML (bold, bullet lists).'),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, default='', help_text='e.g. "100% Cotton" or "60% Cotton, 40% Polyester"', max_length=200),
        ),
    ]
