# Generated by Django 5.2.9 on 2026-03-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0052_order_delivery_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
