# Generated by Django 5.2.9 on 2026-03-22 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0053_order_delivered_email_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=200, unique=True)),
                ('count', models.PositiveIntegerField(default=1)),
                ('last_searched', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Search Term',
                'ordering': ['-count'],
            },
        ),
        migrations.CreateModel(
            name='AbandonedCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('items_snapshot', models.JSONField(default=list)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abandoned_cart', to='store.customer')),
            ],
            options={
                'verbose_name': 'Abandoned Cart',
            },
        ),
    ]
