# Generated by Django 5.2.9 on 2026-03-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0054_search_term_abandoned_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guest_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
