# Generated by Django 5.2.9 on 2026-03-28 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0056_password_reset_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeExchangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved — Replacement Shipping'), ('REJECTED', 'Rejected'), ('STORE_CREDIT_ISSUED', 'Store Credit Issued (size OOS)'), ('COMPLETED', 'Completed')], default='REQUESTED', max_length=25)),
                ('admin_notes', models.TextField(blank=True, default='', help_text='Internal notes (not shown to customer).')),
                ('credit_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Store credit issued if requested size was out of stock.', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_requests', to='store.order')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_requests', to='store.orderitem')),
                ('requested_sku', models.ForeignKey(blank=True, help_text='The new size/SKU the customer wants.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_requests_incoming', to='store.sku')),
            ],
            options={
                'verbose_name': 'Size Exchange Request',
                'verbose_name_plural': 'Size Exchange Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store_credit', to='store.customer')),
            ],
            options={
                'verbose_name': 'Store Credit',
                'verbose_name_plural': 'Store Credits',
            },
        ),
    ]
