# Generated by Django 5.2.9 on 2026-04-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0058_usernotification_pushsubscription_sitebanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='awb_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='courier_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='sku',
            name='weight_grams',
            field=models.PositiveIntegerField(default=200, help_text='Weight in grams (used for shipping)'),
        ),
    ]
