# Generated by Django 5.2.9 on 2026-04-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0059_sku_weight_order_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='size_chart',
            field=models.ImageField(blank=True, help_text='Size chart image shown on the product page (upload from Canva/Photoshop)', max_length=255, null=True, upload_to='size_charts/'),
        ),
    ]
