[phases.setup]
nixPkgs = ["python312", "python312Packages.pip"]
aptPkgs = ["libpango-1.0-0", "libpangocairo-1.0-0", "libcairo2", "libgdk-pixbuf-2.0-0", "libglib2.0-0", "libharfbuzz0b", "fontconfig", "libfreetype6"]
