[phases.setup]
nixPkgs = ["python312", "python312Packages.pip", "gcc", "cairo", "pkg-config", "gobject-introspection", "pango", "gdk-pixbuf"]

[variables]
PKG_CONFIG_PATH = "/root/.nix-profile/lib/pkgconfig:/root/.nix-profile/share/pkgconfig"
